### ISSUE TITLE
"No Subsystems"

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#15]
The "No Subsystems" was probably originally thought to give a number of subsystems in each, but "No subsystems" is incorrect. So either remove for now, or fix the count (could be that there is a timing/watch error and render happens while subsystems are loaded, or could be that number of subsystems supposed to be part of ProjectDefinition)

![image](https://user-images.githubusercontent.com/106693/125056925-00a76f80-e0a9-11eb-827f-b117ea31f9e2.png)

**Comment by grzegorekb** [comment]
text removed, as discussed
