### ISSUE TITLE
Fix Layout for Plans

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#23]
I have changed the strategy to call Stripe's API from the `sensetif-datasource-plugin` and return their objects directly.

`Plans.tsx` and `PlansList.tsx` is trying to format that nicely, but I can't figure it out.

Preferred;
1. Make each "plan" a box, not occupying the whole width
2. Stack plans next to each other
3. Pricing in a "reasonable" way, i.e. Yearly possibly larger, with "% OFF" from the "Monthly" fee. The "Onetime" should change to "10 years Prepaid" or something like that. Single click "subscribe" is preferred.
4. I am going to utilize Images later, but has no material yet. Suggestions welcome...

**Comment by niclash** [comment]
When the boxes wrap to new lines, they "float together" and become confusing.

**Comment by grzegorekb** [comment]
@niclash fixed
