### ISSUE TITLE
Manual monthly data input

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#28]
There are "timeseries" that needs to be populated manually, and need a system for that.

Primary use case;
Entry of Monthly data, such as electricity bills. A table should be shown, Jan-Dec and I should be able to change "year", "project" and add columns, where columns connects to subsystem/datapoint. The table should be populated with already entered data. On "submit" the table is pushed to the backend. The table should be saved and reused for next time.

**Comment by niclash** [comment]
This should be a Panel, but not a new git repository (see #45).

Config page will establish which datapoints that can have values set. I think starting with the Table panel is quite reasonable.

The Rendering should be an editable table, with one column per datapoint.

Table is populated from database, just as usual. But each cell should be editable. Any modified value should be sent to backend directly, with the timestamp of the table row.

It must be possible to easily adjust table row timestamps, such as snapping to Month, Week, Day and Hour by a single click. Probably it is a good idea to get the datapoint definition and look at the poll interval to decide what that snap is.

It should be possible to delete a cell. That requires the original timestamp to be preserved and sent back.

Header in table should present Name and Unit for each datapoint.

**Comment by grzegorekb** [comment]
Did you have a chance to test it? Do you think it's enough for now? I think there are still some requirements that were not met so far:

> It must be possible to easily adjust table row timestamps, such as snapping to Month, Week, Day and Hour by a single click. Probably it is a good idea to get the datapoint definition and look at the poll interval to decide what that snap is.
☝️  this one is not addressed - timestamps are not editable in the current solution.

> It should be possible to delete a cell. That requires the original timestamp to be preserved and sent back.
☝️ rows cannot be deleted (do we have such an endpoint to delete a data point?)

@niclash
