### ISSUE TITLE
Title in Datapoints.tsx

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#4]
When having the Datapoints tab open, it is not possible to see the Project and Subsystem.

I suggest that large title is "Subsystem Title" and then have a second line, in smaller font with "projectname - subsystemname".

![image](https://user-images.githubusercontent.com/106693/124444029-7bf1e400-dd7e-11eb-91db-acd9cb969e7f.png)

**Comment by grzegorekb** [comment]
fixed
