### ISSUE TITLE
Title in Subsystems.tsx

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#5]
I think the title in Subsystems.tsx can be improved. It is currently showing "Project: ${project.name}"

Main title should be "${project.title}" (no "Project" word) and in a smaller font under is the "${project.name}".

![image](https://user-images.githubusercontent.com/106693/124444668-2407ad00-dd7f-11eb-86b6-3949aa5c77bf.png)

**Comment by grzegorekb** [comment]
fixed
