### ISSUE TITLE
Show values in Import Things Network

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#52]
After "Fetching" the device list and clicking on a device, I get all the values available (formatting is not great, see attachment). But it would also be neat to see the value for each, since there are devices that optional sensors or inputs.

![image](https://github.com/Sensetif/sensetif-app-plugin/assets/106693/b6749fa6-cad5-4188-8e1c-89449c1f0907)

**Comment by niclash** [comment]
![image](https://github.com/Sensetif/sensetif-app-plugin/assets/106693/ab62ba6e-56c2-4795-8487-99fd549b84e1)

**Comment by grzegorekb** [comment]
@niclash 
This view was deleted - in the latest version we go directly to Confirmation Screen after clicking on the particular device
1. devices view
<img width="1577" alt="image" src="https://github.com/Sensetif/sensetif-app-plugin/assets/8106010/6a08cc44-26a3-4a44-a1c0-6808447b15bd">

2. after clicked on `room 7`
<img width="1577" alt="image" src="https://github.com/Sensetif/sensetif-app-plugin/assets/8106010/fe0db77d-ce76-471f-a2b4-32517578e372">
