### ISSUE TITLE
Timeout "Loading Payload..."

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#57]
There is no timeout on the "Loading Payload..." spinner.

1. If possible, the current table has "Created" and "Updated". The "Updated" refers to when it was last modified its settings, but there should be a value available for when the device last sent a message to TTN. It is available in Console, so I assume it is accessible. IF longer ago than 12 hours, then it can timeout immediately and say "Seems to be not available". And change "Updated" to "Last Seen" if the above is possible.

2. Timeout can be 10 seconds.

3. If ALL devices in the list has no messages, then propose "It seems that you have not Activated Storage Integration in the Things Network console."

![image](https://github.com/Sensetif/sensetif-app-plugin/assets/106693/f73b6172-df77-48d8-a06f-e627b5651ee1)

**Comment by niclash** [comment]
I think this has been solved,right?

**Comment by grzegorekb** [comment]
> I think this has been solved,right?

Correct. Can be closed.
