### ISSUE TITLE
"Title" in query editor

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#59]
Use "Title" rather than "Name" in these places.

![image](https://github.com/Sensetif/sensetif-app-plugin/assets/106693/d3fd12ef-18c6-48af-b144-5b8c8bfc431e)

**Comment by grzegorekb** [comment]
Implemented here
https://github.com/Sensetif/sensetif-app-plugin/commit/92a52b760e2701f747502fbe4ea2ed576b5f8985
