### ISSUE TITLE
TTN Import not populating datapoints

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#66]
I get the list of devices, but when selecting any of the devices, there are no datapoints listed at all.

See screenshots.

It doesn't happen all the time, but on this particular project it seems to always fail.

**Comment by niclash** [comment]
![Screenshot_20231004_175146](https://github.com/Sensetif/sensetif-app-plugin/assets/106693/640d134f-3393-4bfa-a3f9-3de398340008)
![Screenshot_20231004_175117](https://github.com/Sensetif/sensetif-app-plugin/assets/106693/39186472-f6b1-4439-9d81-32d79c44f238)

**Comment by grzegorekb** [comment]
As discussed. `fPort` at the top of that modal is clickable radio button.
It populates list once fPort is selected.

With this commit: https://github.com/Sensetif/sensetif-app-plugin/commit/ee6266fd8427dce94205cca1148bd90fe1e11640 I'm selecting 1st found fPort as default.
